import { Prisma } from "@prisma/client";

// 自定义菜单创建输入
interface CustomMenuCreateInput extends Prisma.MenuCreateInput {
  id: number;
}

export const menus: CustomMenuCreateInput[] = [
  {
    id: 1,
    name: "默认",
    code: "Default",
    type: "MENU",
    pid: null, // 顶级菜单为null
    path: "/default",
    redirect: "/default/home",
    icon: "fe:home",
    component: null,
    layout: "normal",
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 2,
    name: "首页",
    code: "Home",
    type: "MENU",
    pid: 1,
    path: "/default/home",
    redirect: null,
    icon: "fe:home",
    component: "/src/views/home/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 9,
    name: "基础功能",
    code: "Base",
    type: "MENU",
    pid: null,
    path: "/base",
    redirect: "/base/components",
    icon: "fe:layout",
    component: null,
    layout: "",
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 10,
    name: "基础组件",
    code: "BaseComponents",
    type: "MENU",
    pid: 9,
    path: "/base/components",
    redirect: null,
    icon: "mdi:ab-testing",
    component: "/src/views/base/index.vue",
    layout: "",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
  },
  {
    id: 11,
    name: "Unocss组件",
    code: "Unocss",
    type: "MENU",
    pid: 9,
    path: "/base/unocss",
    redirect: null,
    icon: "mdi:abugida-thai",
    component: "/src/views/base/unocss.vue",
    layout: "",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
  },
  {
    id: 12,
    name: "KeepAlive组件",
    code: "KeepAlive",
    type: "MENU",
    pid: 9,
    path: "/base/keep-alive",
    redirect: null,
    icon: "mdi:account-circle-outline",
    component: "/src/views/base/keep-alive.vue",
    layout: "",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
  },
  {
    id: 100,
    name: "系统管理",
    code: "System",
    type: "MENU",
    pid: null,
    path: "/system",
    redirect: "/system/user",
    icon: "fe:layout",
    component: null,
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 101,
    name: "用户管理",
    code: "User",
    type: "MENU",
    pid: 100,
    path: "/system/user",
    redirect: null,
    icon: "fe:layout",
    component: "/src/views/system/user/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 102,
    name: "菜单管理",
    code: "menu",
    type: "MENU",
    pid: 100,
    path: "/system/menu",
    redirect: null,
    icon: "fe:layout",
    component: "/src/views/system/menu/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 103,
    name: "角色管理",
    code: "Role",
    type: "MENU",
    pid: 100,
    path: "/system/role",
    redirect: null,
    icon: "fe:layout",
    component: "/src/views/system/role/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
];
