import { Prisma } from "@prisma/client";

// 自定义菜单创建输入
interface CustomMenuCreateInput extends Prisma.MenuCreateInput {
  id: number;
}

export const menus: CustomMenuCreateInput[] = [
  {
    id: 1,
    name: "首页",
    code: "Home",
    type: "MENU",
    pid: null,
    path: "/home",
    redirect: null,
    icon: "fe:home",
    component: "/src/views/home/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    extraData: '{"withContentCard": false}',
  },
  {
    id: 2,
    name: "系统管理",
    code: "System",
    type: "MENU",
    pid: null,
    path: "/system",
    redirect: "/system/user",
    icon: "fe:layout",
    component: null,
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 3,
    name: "用户管理",
    code: "User",
    type: "MENU",
    pid: 2,
    path: "/system/user",
    redirect: null,
    icon: "fe:layout",
    component: "/src/views/system/user/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 4,
    name: "菜单管理",
    code: "MenuManager",
    type: "MENU",
    pid: 2,
    path: "/system/menu",
    redirect: null,
    icon: "solar:checklist-broken",
    component: "/src/views/system/menu/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 5,
    name: "角色管理",
    code: "Role",
    type: "MENU",
    pid: 2,
    path: "/system/role",
    redirect: null,
    icon: "solar:user-speak-outline",
    component: "/src/views/system/role/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 6,
    name: "个人中心",
    code: "UserCenter",
    type: "MENU",
    pid: null,
    path: "/user-center",
    redirect: null,
    icon: "solar:user-id-broken",
    component: "/src/views/user-center/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    extraData: '{"withContentCard": false}',
  },
  {
    id: 7,
    name: "新增",
    code: "system:user:create",
    type: "BUTTON",
    pid: 3,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 8,
    name: "公告管理",
    code: "NoticeManager",
    type: "DIRECTORY",
    pid: null,
    path: "/notice",
    redirect: "/notice/notice",
    icon: "material-symbols:signpost-outline",
    component: null,
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 9,
    name: "公告",
    code: "Notice",
    type: "MENU",
    pid: 8,
    path: "/notice/notice",
    redirect: null,
    icon: "iconoir:post",
    component: "/src/views/notice/notice/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 10,
    name: "待办事项",
    code: "Todo",
    type: "MENU",
    pid: 8,
    path: "/notice/todo",
    redirect: null,
    icon: "vscode-icons:file-type-light-todo",
    component: "/src/views/notice/todo/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    extraData: '{"withContentCard": false}',
  },
  {
    id: 11,
    name: "医院管理",
    code: "Hospital",
    type: "DIRECTORY",
    pid: null,
    path: "/hospital",
    redirect: "/hospital/department",
    icon: "tdesign:hospital",
    component: null,
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 12,
    name: "科室管理",
    code: "Department",
    type: "MENU",
    pid: 11,
    path: "/hospital/department",
    redirect: null,
    icon: "mingcute:department-line",
    component: "/src/views/hospital/department/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: "科室管理",
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 13,
    name: "医生管理",
    code: "Doctor",
    type: "MENU",
    pid: 11,
    path: "/hospital/doctor",
    redirect: null,
    icon: "hugeicons:doctor-02",
    component: "/src/views/hospital/doctor/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 14,
    name: "患者管理",
    code: "PATIENT",
    type: "MENU",
    pid: 11,
    path: "/hospital/patient",
    redirect: "",
    icon: "material-symbols:recent-patient-outline",
    component: "/src/views/hospital/patient/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: "患者管理",
    show: true,
    enable: true,
    order: 0,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 15,
    name: "排班挂号",
    code: "Schedule",
    type: "DIRECTORY",
    pid: null,
    path: "/schedule",
    redirect: "/schedule/hospital-schedule",
    icon: "uil:schedule",
    component: "",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-25T11:57:43.554Z",
    updatedTime: "2024-12-25T03:59:43.032Z",
  },
  {
    id: 16,
    name: "医生排班",
    code: "DoctorSchedule",
    type: "MENU",
    pid: 15,
    path: "/schedule/doctor-schedule",
    redirect: null,
    icon: "ant-design:schedule-outlined",
    component: "/src/views/schedule/doctor-schedule/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-25T11:59:05.035Z",
    updatedTime: null,
    extraData: null,
  },
  {
    id: 17,
    name: "我的排班",
    code: "MySchedule",
    type: "MENU",
    pid: 15,
    path: "/schedule/my-schedule",
    redirect: null,
    icon: "material-symbols-light:schedule-send-outline",
    component: "/src/views/schedule/my-schedule/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-26T10:39:50.317Z",
    updatedTime: "2024-12-27T01:58:04.222Z",
  },
  {
    id: 18,
    name: "患者模块",
    code: "PatientModule",
    type: "DIRECTORY",
    pid: null,
    path: "/patient",
    redirect: "/patient/patientHome",
    icon: null,
    component: "",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-30T06:59:31.945Z",
    updatedTime: "2024-12-30T06:59:45.295Z",
    extraData: '{"withContentCard":true}',
  },
  {
    id: 19,
    name: "患者首页",
    code: "PatientHome",
    type: "MENU",
    pid: 18,
    path: "/patient/patientHome",
    redirect: "",
    icon: null,
    component: "/src/views/home/patientHome.vue",
    layout: "full-content",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-30T07:00:11.997Z",
    updatedTime: "2024-12-30T07:01:26.757Z",
    extraData: '{"withContentCard":false}',
  },
  {
    id: 20,
    name: "预约挂号",
    code: "Appointment",
    type: "MENU",
    pid: 18,
    path: "/patient/appointment",
    redirect: "",
    icon: null,
    component: "/src/views/patient-module/appointment/index.vue",
    layout: "full-content",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-30T07:02:34.926Z",
    updatedTime: "2024-12-30T07:02:42.503Z",
    extraData: '{"withContentCard":true}',
  },
  {
    id: 21,
    name: "我的挂号",
    code: "MyAppointment",
    type: "MENU",
    pid: 18,
    path: "/patient/my-appointment",
    redirect: "",
    icon: null,
    component: "/src/views/patient-module/my-appointment/index.vue",
    layout: "full-content",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-30T08:23:32.316Z",
    updatedTime: "2024-12-30T08:23:32.316Z",
    extraData: '{"withContentCard":true}',
  },
  {
    id: 22,
    name: "我的病例",
    code: "MyCases",
    type: "MENU",
    pid: 18,
    path: "/patient/my-cases",
    redirect: "",
    icon: null,
    component: "/src/views/patient-module/my-cases/index.vue",
    layout: "full-content",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-31T03:39:56.860Z",
    updatedTime: "2024-12-31T03:39:56.860Z",
    extraData: '{"withContentCard":true}',
  },
  {
    id: 23,
    name: "医生首页",
    code: "DoctorHome",
    type: "MENU",
    pid: 24,
    path: "/doctorHome",
    redirect: "",
    icon: "fe:home",
    component: "/src/views/home/doctorHome.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2024-12-31T09:51:24.556Z",
    updatedTime: "2025-01-02T06:30:18.075Z",
    extraData: '{"withContentCard":false}',
  },
  {
    id: 24,
    name: "医生模块",
    code: "DoctorModule",
    type: "DIRECTORY",
    pid: null,
    path: "/doctor",
    redirect: "/doctor/doctorHome",
    icon: "hugeicons:doctor-01",
    component: null,
    layout: "full-content",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-01-02T06:30:12.256Z",
    updatedTime: "2025-01-02T06:30:12.256Z",
    extraData: '{"withContentCard":true}',
  },
  {
    id: 25,
    name: "医生叫号",
    code: "DoctorAppointment",
    type: "MENU",
    pid: 24,
    path: "/doctor/appointment",
    redirect: "",
    icon: "mdi:bell-ring-outline",
    component: "/src/views/doctor-module/appointment/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: "",
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-01-02T06:31:25.176Z",
    updatedTime: "2025-01-02T06:55:09.911Z",
    extraData: '{"withContentCard":false}',
  },
];
