import { Prisma } from "@prisma/client";
// 菜单数据类型定义
interface CustomMenuCreateInput extends Prisma.MenuCreateInput {
  id: number;
}

// 菜单初始化数据
export const menus: CustomMenuCreateInput[] = [
  {
    id: 1,
    name: "首页",
    code: "Home",
    type: "MENU",
    pid: null,
    path: "/home",
    redirect: null,
    icon: "fe:home",
    component: "/src/views/home/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: false,
    extraData: '{"withContentCard": false}',
  },
  {
    id: 2,
    name: "系统管理",
    code: "System",
    type: "DIRECTORY",
    pid: null,
    path: "/system",
    redirect: "/system/user",
    icon: "fe:layout",
    component: null,
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 3,
    name: "用户管理",
    code: "User",
    type: "MENU",
    pid: 2,
    path: "/system/user",
    redirect: null,
    icon: "fe:layout",
    component: "/src/views/system/user/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: null,
  },
  {
    id: 4,
    name: "菜单管理",
    code: "MenuManager",
    type: "MENU",
    pid: 2,
    path: "/system/menu",
    redirect: null,
    icon: "solar:checklist-broken",
    component: "/src/views/system/menu/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: null,
  },
  {
    id: 5,
    name: "角色管理",
    code: "Role",
    type: "MENU",
    pid: 2,
    path: "/system/role",
    redirect: null,
    icon: "solar:user-speak-outline",
    component: "/src/views/system/role/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: null,
  },
  {
    id: 6,
    name: "个人中心",
    code: "UserCenter",
    type: "MENU",
    pid: null,
    path: "/user-center",
    redirect: null,
    icon: "solar:user-id-broken",
    component: "/src/views/user-center/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard": false}',
  },
  {
    id: 7,
    name: "新增",
    code: "system:user:create",
    type: "BUTTON",
    pid: 3,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: null,
  },
  {
    id: 8,
    name: "公告管理",
    code: "NoticeManager",
    type: "DIRECTORY",
    pid: null,
    path: "/notice",
    redirect: "/notice/notice",
    icon: "material-symbols:signpost-outline",
    component: null,
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: null,
  },
  {
    id: 9,
    name: "公告",
    code: "Notice",
    type: "MENU",
    pid: 8,
    path: "/notice/notice",
    redirect: null,
    icon: "iconoir:post",
    component: "/src/views/notice/notice/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: null,
  },
  {
    id: 10,
    name: "待办事项",
    code: "Todo",
    type: "MENU",
    pid: 8,
    path: "/notice/todo",
    redirect: null,
    icon: "vscode-icons:file-type-light-todo",
    component: "/src/views/notice/todo/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard": false}',
  },
  {
    id: 11,
    name: "博客",
    code: "Blog",
    type: "DIRECTORY",
    pid: 23,
    path: "/blog",
    redirect: "/blog/home",
    icon: "tabler:brand-blogger",
    component: null,
    layout: "blog",
    keepAlive: false,
    method: null,
    description: "博客系统",
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-09-02T09:22:18.886Z",
    needLogin: false,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 12,
    name: "博客首页",
    code: "BlogHome",
    type: "MENU",
    pid: 11,
    path: "/blog/home",
    redirect: null,
    icon: null,
    component: "/src/views/blog/home/index.vue",
    layout: "blog",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: false,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 13,
    name: "系统配置",
    code: "SystemConfig",
    type: "MENU",
    pid: 2,
    path: "/system/config",
    redirect: null,
    icon: "material-symbols:settings-outline",
    component: "/src/views/system/config/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 14,
    name: "u3c3",
    code: "U3C3",
    type: "MENU",
    pid: 15,
    path: "/resource/u3c3",
    redirect: null,
    icon: "tabler:subtask",
    component: "/src/views/other/resource/u3c3/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 15,
    name: "资源库",
    code: "Resource",
    type: "DIRECTORY",
    pid: null,
    path: "/resource",
    redirect: "/resource/u3c3",
    icon: "material-symbols:database-outline",
    component: null,
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard":false}',
  },
  {
    id: 16,
    name: "小诚",
    code: "Xiaocheng",
    type: "DIRECTORY",
    pid: null,
    path: "/xiaocheng",
    redirect: "/xiaocheng/task",
    icon: "material-symbols:accessible-forward-sharp",
    component: null,
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 17,
    name: "任务列表",
    code: "XiaochengTask",
    type: "MENU",
    pid: 16,
    path: "/xiaocheng/task",
    redirect: null,
    icon: "material-symbols:task-outline-sharp",
    component: "/src/views/xiaocheng/task/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 18,
    name: "爬取日志",
    code: "u3c3Log",
    type: "MENU",
    pid: 15,
    path: "/resource/u3c3_loh",
    redirect: null,
    icon: "material-symbols:3d-rotation",
    component: "/src/views/other/resource/u3c3Log/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:51:07.829Z",
    updatedTime: "2025-08-25T09:51:07.829Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 19,
    name: "操作日志",
    code: "SystemOpLog",
    type: "MENU",
    pid: 2,
    path: "/system/op-log",
    redirect: null,
    icon: "solar:dialog-2-broken",
    component: "/src/views/system/oplog/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:54:09.488Z",
    updatedTime: "2025-08-25T09:54:09.488Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 20,
    name: "部门管理",
    code: "SystemDepartment",
    type: "MENU",
    pid: 2,
    path: "/system/department",
    redirect: null,
    icon: "mingcute:department-line",
    component: "/src/views/system/department/index.vue",
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-08-25T09:55:37.619Z",
    updatedTime: "2025-08-25T09:55:37.619Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 21,
    name: "导航管理",
    code: "Navigation",
    type: "DIRECTORY",
    pid: 23,
    path: "/navigation",
    redirect: "/navigation/admin",
    icon: "material-symbols:navigation-outline",
    component: null,
    layout: "normal",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-09-01T13:15:07.430Z",
    updatedTime: "2025-09-02T09:22:10.203Z",
    needLogin: false,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 22,
    name: "导航",
    code: "NavigationAdmin",
    type: "MENU",
    pid: 21,
    path: "/navigation/admin",
    redirect: null,
    icon: "material-symbols:assistant-navigation-outline-rounded",
    component: "/src/views/navigation/admin/index.vue",
    layout: "public",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-09-01T13:16:01.727Z",
    updatedTime: "2025-09-02T09:30:14.929Z",
    needLogin: false,
    extraData: '{"withContentCard":true}',
  },
  {
    id: 23,
    name: "公开页面",
    code: "Public",
    type: "DIRECTORY",
    pid: null,
    path: "/public",
    redirect: null,
    icon: null,
    component: null,
    layout: "public",
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    createdTime: "2025-09-02T09:21:57.251Z",
    updatedTime: "2025-09-02T09:26:41.458Z",
    needLogin: true,
    extraData: '{"withContentCard":true}',
  },
];
