import { OperationStatus, OperationType } from "@prisma/client";
import { ICreateOperationLog } from "../../src/modules/sys/operation-log/typings";

/**
 * 操作日志初始化数据
 * 用于演示和测试操作日志功能
 */
export const operationLogInitData: ICreateOperationLog[] = [
  {
    userId: 1,
    username: "admin",
    operationType: OperationType.LOGIN,
    module: "用户管理",
    description: "管理员登录系统",
    method: "POST",
    url: "/api/user/login",
    params: JSON.stringify({
      username: "admin",
      password: "******",
    }),
    result: JSON.stringify({
      success: true,
      message: "登录成功",
      token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    }),
    status: OperationStatus.SUCCESS,
    ipAddress: "127.0.0.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    duration: 156,
  },
  {
    userId: 1,
    username: "admin",
    operationType: OperationType.CREATE,
    module: "用户管理",
    description: "创建新用户",
    method: "POST",
    url: "/api/user/create",
    params: JSON.stringify({
      username: "testuser",
      name: "测试用户",
      email: "test@example.com",
    }),
    result: JSON.stringify({
      success: true,
      message: "用户创建成功",
      data: { id: 2, username: "testuser" },
    }),
    status: OperationStatus.SUCCESS,
    ipAddress: "127.0.0.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    duration: 234,
  },
  {
    userId: 1,
    username: "admin",
    operationType: OperationType.UPDATE,
    module: "系统配置",
    description: "更新系统配置",
    method: "PUT",
    url: "/api/system/config/update",
    params: JSON.stringify({
      key: "site_name",
      value: "JDM管理系统",
    }),
    result: JSON.stringify({
      success: true,
      message: "配置更新成功",
    }),
    status: OperationStatus.SUCCESS,
    ipAddress: "127.0.0.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    duration: 89,
  },
  {
    userId: 2,
    username: "testuser",
    operationType: OperationType.VIEW,
    module: "用户管理",
    description: "查看用户列表",
    method: "GET",
    url: "/api/user/list",
    params: JSON.stringify({
      page: 1,
      pageSize: 10,
    }),
    result: JSON.stringify({
      success: true,
      data: { total: 2, list: [] },
    }),
    status: OperationStatus.SUCCESS,
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    duration: 45,
  },
  {
    userId: undefined,
    username: "-",
    operationType: OperationType.LOGIN,
    module: "用户管理",
    description: "用户登录失败",
    method: "POST",
    url: "/api/user/login",
    params: JSON.stringify({
      username: "wronguser",
      password: "******",
    }),
    result: JSON.stringify({
      success: false,
      message: "用户名或密码错误",
    }),
    status: OperationStatus.FAILED,
    errorMessage: "用户名或密码错误",
    ipAddress: "192.168.1.200",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    duration: 123,
  },
  {
    userId: 1,
    username: "admin",
    operationType: OperationType.DELETE,
    module: "用户管理",
    description: "删除用户",
    method: "DELETE",
    url: "/api/user/delete/3",
    params: JSON.stringify({
      id: 3,
    }),
    result: JSON.stringify({
      success: true,
      message: "用户删除成功",
    }),
    status: OperationStatus.SUCCESS,
    ipAddress: "127.0.0.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    duration: 67,
  },
  {
    userId: 1,
    username: "admin",
    operationType: OperationType.EXPORT,
    module: "操作日志",
    description: "导出操作日志",
    method: "POST",
    url: "/api/system/operation-log/export",
    params: JSON.stringify({
      startTime: "2024-01-01",
      endTime: "2024-12-31",
    }),
    result: JSON.stringify({
      success: true,
      message: "导出成功",
      data: { fileName: "operation_log_20240115.xlsx" },
    }),
    status: OperationStatus.SUCCESS,
    ipAddress: "127.0.0.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    duration: 1234,
  },
  {
    userId: 2,
    username: "testuser",
    operationType: OperationType.VIEW,
    module: "通知公告",
    description: "查看通知详情",
    method: "GET",
    url: "/api/notice/detail/1",
    params: JSON.stringify({
      id: 1,
    }),
    result: JSON.stringify({
      success: true,
      data: {
        id: 1,
        title: "系统维护通知",
        content: "系统将于今晚进行维护...",
      },
    }),
    status: OperationStatus.SUCCESS,
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    duration: 78,
  },
];
