import { Prisma } from "@prisma/client";
// 系统配置数据类型定义

interface CustomSysConfigCreateInput extends Prisma.SysConfigCreateInput {}

// 系统配置初始化数据
export const sysConfigs: CustomSysConfigCreateInput[] = [
  {
    description: "系统版权信息",
    category: "system",
    key: "copyright",
    value: "© 2024 JDM System. All rights reserved.",
    isPublic: true,
    isSystem: true,
    sortOrder: 1,
    type: "STRING",
    name: "版权信息",
  },
  {
    description: "系统初始化状态",
    category: "system",
    key: "initialized",
    value: "true",
    isPublic: false,
    isSystem: true,
    sortOrder: 2,
    type: "BOOLEAN",
    name: "初始化状态",
  },
  {
    description: "网站名称",
    category: "site",
    key: "site_name",
    value: "JDM管理系统",
    isPublic: true,
    isSystem: false,
    sortOrder: 3,
    type: "STRING",
    name: "网站名称",
  },
  {
    description: "网站描述",
    category: "site",
    key: "site_description",
    value: "基于NestJS和React的现代化管理系统",
    isPublic: true,
    isSystem: false,
    sortOrder: 4,
    type: "STRING",
    name: "网站描述",
  },
  {
    description: "系统版本号",
    category: "system",
    key: "version",
    value: "1.0.0",
    isPublic: true,
    isSystem: true,
    sortOrder: 5,
    type: "STRING",
    name: "系统版本",
  },
  {
    description: "系统主题色",
    category: "theme",
    key: "primary_color",
    value: "#1890ff",
    isPublic: true,
    isSystem: false,
    sortOrder: 6,
    type: "STRING",
    name: "主题色",
  },
  {
    description: "每页显示条数",
    category: "pagination",
    key: "page_size",
    value: "10",
    isPublic: true,
    isSystem: false,
    sortOrder: 7,
    type: "NUMBER",
    name: "分页大小",
  },
  {
    description: "文件上传大小限制(MB)",
    category: "upload",
    key: "max_file_size",
    value: "10",
    isPublic: false,
    isSystem: true,
    sortOrder: 8,
    type: "NUMBER",
    name: "文件大小限制",
  },
  {
    description: "系统维护模式",
    category: "system",
    key: "maintenance_mode",
    value: "false",
    isPublic: true,
    isSystem: true,
    sortOrder: 9,
    type: "BOOLEAN",
    name: "维护模式",
  },
  {
    description: "默认语言",
    category: "locale",
    key: "default_language",
    value: "zh-CN",
    isPublic: true,
    isSystem: false,
    sortOrder: 10,
    type: "STRING",
    name: "默认语言",
  },
];
