/*
 * @Author: jdm
 * @Date: 2024-09-04 15:25:50
 * @LastEditors: jdm
 * @LastEditTime: 2024-09-04 15:54:17
 * @FilePath: \APP\prisma\initData\sysConfig.ts
 * @Description:
 *
 */
import { Prisma } from "@prisma/client";

export const sysConfig: Prisma.SysConfigCreateManyInput[] = [
  {
    key: "system.isInit",
    name: "系统初始化状态",
    value: "false",
    type: "BOOLEAN",
    category: "SYSTEM",
    description:
      "数据库是否经过初始化操作，如果经过初始化，则不再执行初始化操作",
    isSystem: true,
    isPublic: false,
    sortOrder: 1,
  },
  {
    key: "system.siteName",
    name: "网站名称",
    value: "Play Home Yeah！",
    type: "STRING",
    category: "SYSTEM",
    description: "网站名称",
    isSystem: true,
    isPublic: false,
    sortOrder: 2,
  },
  {
    key: "system.siteDescription",
    name: "网站描述",
    value: "基于NestJS的系统管理平台",
    type: "STRING",
    category: "SYSTEM",
    description: "网站描述",
    isSystem: true,
    isPublic: false,
    sortOrder: 3,
  },
  {
    key: "system.version",
    name: "系统版本号",
    value: "1.0.0",
    type: "STRING",
    category: "SYSTEM",
    description: "系统版本",
    isSystem: true,
    isPublic: true,
    sortOrder: 4,
  },
  {
    key: "system.copyright",
    name: "系统的版权信息",
    value: "Copyright © 2025 Jay",
    type: "STRING",
    category: "SYSTEM",
    description: "系统版权信息",
    isSystem: true,
    isPublic: true,
    sortOrder: 0,
  },
  {
    key: "email.smtp.host",
    name: "SMTP服务器地址",
    value: "smtp.qq.com",
    type: "STRING",
    category: "EMAIL",
    description: "SMTP服务器地址",
    isSystem: false,
    isPublic: false,
    sortOrder: 10,
  },
  {
    key: "email.smtp.port",
    name: "SMTP服务器端口",
    value: "587",
    type: "NUMBER",
    category: "EMAIL",
    description: "SMTP服务器端口",
    isSystem: false,
    isPublic: false,
    sortOrder: 11,
  },
  {
    key: "email.smtp.username",
    name: "SMTP用户名",
    value: "",
    type: "EMAIL",
    category: "EMAIL",
    description: "SMTP用户名",
    isSystem: false,
    isPublic: false,
    sortOrder: 12,
  },
  {
    key: "email.smtp.password",
    name: "SMTP密码",
    value: "",
    type: "PASSWORD",
    category: "EMAIL",
    description: "SMTP密码",
    isSystem: false,
    isPublic: false,
    sortOrder: 13,
  },
  {
    key: "upload.maxFileSize",
    name: "最大文件上传大小(字节)",
    value: "10485760",
    type: "NUMBER",
    category: "UPLOAD",
    description: "最大文件上传大小",
    isSystem: true,
    isPublic: false,
    sortOrder: 20,
  },
  {
    key: "upload.allowedTypes",
    name: "允许上传的文件类型",
    value: '["jpg","jpeg","png","gif","pdf","doc","docx","xls","xlsx"]',
    type: "ARRAY",
    category: "UPLOAD",
    description: "允许上传的文件类型",
    isSystem: true,
    isPublic: false,
    sortOrder: 21,
  },
  {
    key: "security.sessionTimeout",
    name: "会话超时时间(秒)",
    value: "7200",
    type: "NUMBER",
    category: "SECURITY",
    description: "会话超时时间",
    isSystem: false,
    isPublic: false,
    sortOrder: 30,
  },
  {
    key: "security.passwordPolicy",
    name: "密码策略配置",
    value:
      '{"minLength":8,"requireUppercase":true,"requireLowercase":true,"requireNumbers":true,"requireSpecialChars":false}',
    type: "JSON",
    category: "SECURITY",
    description: "密码策略配置",
    isSystem: false,
    isPublic: false,
    sortOrder: 31,
  },
];
