import { inject, injectable } from "inversify";
import { PrismaDB } from "../../../db";

const menu = [
  {
    id: 1,
    name: "默认",
    code: "Default",
    type: "MENU",
    pid: null,
    path: "/default",
    redirect: "/default/home",
    icon: "fe:layout",
    component: null,
    layout: "normal",
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 2,
    name: "首页",
    code: "Home",
    type: "MENU",
    pid: 1,
    path: "/default/home",
    icon: "fe:layout",
    component: "/src/views/home/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 9,
    name: "基础功能",
    code: "Base",
    type: "MENU",
    pid: null,
    path: "/base",
    redirect: "/base/components",
    icon: "fe:layout",
    component: null,
    layout: "",
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 10,
    name: "基础组件",
    code: "BaseComponents",
    type: "MENU",
    pid: 9,
    path: "/base/components",
    redirect: null,
    icon: "mdi:ab-testing",
    component: "/src/views/base/index.vue",
    layout: null,
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
  },
  {
    id: 11,
    name: "Unocss组件",
    code: "Unocss",
    type: "MENU",
    pid: 9,
    path: "/base/unocss",
    redirect: null,
    icon: "mdi:abugida-thai",
    component: "/src/views/base/unocss.vue",
    layout: null,
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
  },
  {
    id: 12,
    name: "KeepAlive组件",
    code: "KeepAlive",
    type: "MENU",
    pid: 9,
    path: "/base/keep-alive",
    redirect: null,
    icon: "mdi:account-circle-outline",
    component: "/src/views/base/keep-alive.vue",
    layout: null,
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
  },
  {
    id: 100,
    name: "系统管理",
    code: "System",
    type: "MENU",
    pid: null,
    path: "/system",
    redirect: "/system/user",
    icon: "fe:layout",
    component: null,
    layout: "normal",
    keepAlive: null,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
  {
    id: 101,
    name: "用户管理",
    code: "User",
    type: "MENU",
    pid: 100,
    path: "/system/user",
    redirect: null,
    icon: "fe:layout",
    component: "/src/views/system/user/index.vue",
    layout: "normal",
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
  },
];

@injectable()
export class PermissionService {
  constructor(@inject(PrismaDB) private readonly PrismaDB: PrismaDB) {}
  // 获取菜单
  public async getPermissionList(userId: number) {
    try {
      return {
        data: menu,
        code: 200,
        message: "获取用户信息成功",
      };
      // 删除密码
    } catch (err) {
      console.log(err);
      return err;
    }
  }
}
